//*************************************************************************
//** OPOS POSPrinter Internals
//
//   POS Printer header file for OPOS Controls and Service Objects.
//
//*************************************************************************

typedef [helpstring("OPOS POSPrinter Internals")]
enum
{
    PIDXPtr_AsyncMode                    =  8001,
    PIDXPtr_CharacterSet                 =  8002,
    PIDXPtr_CoverOpen                    =  8003,
    PIDXPtr_ErrorStation                 =  8004,
    PIDXPtr_FlagWhenIdle                 =  8005,
    PIDXPtr_JrnEmpty                     =  8006,
    PIDXPtr_JrnLetterQuality             =  8007,
    PIDXPtr_JrnLineChars                 =  8008,
    PIDXPtr_JrnLineHeight                =  8009,
    PIDXPtr_JrnLineSpacing               =  8010,
    PIDXPtr_JrnLineWidth                 =  8011,
    PIDXPtr_JrnNearEnd                   =  8012,
    PIDXPtr_MapMode                      =  8013,
    PIDXPtr_RecEmpty                     =  8014,
    PIDXPtr_RecLetterQuality             =  8015,
    PIDXPtr_RecLineChars                 =  8016,
    PIDXPtr_RecLineHeight                =  8017,
    PIDXPtr_RecLineSpacing               =  8018,
    PIDXPtr_RecLinesToPaperCut           =  8019,
    PIDXPtr_RecLineWidth                 =  8020,
    PIDXPtr_RecNearEnd                   =  8021,
    PIDXPtr_RecSidewaysMaxChars          =  8022,
    PIDXPtr_RecSidewaysMaxLines          =  8023,
    PIDXPtr_SlpEmpty                     =  8024,
    PIDXPtr_SlpLetterQuality             =  8025,
    PIDXPtr_SlpLineChars                 =  8026,
    PIDXPtr_SlpLineHeight                =  8027,
    PIDXPtr_SlpLinesNearEndToEnd         =  8028,
    PIDXPtr_SlpLineSpacing               =  8029,
    PIDXPtr_SlpLineWidth                 =  8030,
    PIDXPtr_SlpMaxLines                  =  8031,
    PIDXPtr_SlpNearEnd                   =  8032,
    PIDXPtr_SlpSidewaysMaxChars          =  8033,
    PIDXPtr_SlpSidewaysMaxLines          =  8034,
    PIDXPtr_ErrorLevel                   =  8035,
    PIDXPtr_RotateSpecial                =  8036,
    PIDXPtr_CartridgeNotify              =  8037,
    PIDXPtr_JrnCartridgeState            =  8038,
    PIDXPtr_JrnCurrentCartridge          =  8039,
    PIDXPtr_RecCartridgeState            =  8040,
    PIDXPtr_RecCurrentCartridge          =  8041,
    PIDXPtr_SlpPrintSide                 =  8042,
    PIDXPtr_SlpCartridgeState            =  8043,
    PIDXPtr_SlpCurrentCartridge          =  8044,
    PIDXPtr_MapCharacterSet              =  8045,
    PIDXPtr_PageModeDescriptor           =  8046,
    PIDXPtr_PageModeHorizontalPosition   =  8047,
    PIDXPtr_PageModePrintDirection       =  8048,
    PIDXPtr_PageModeStation              =  8049,
    PIDXPtr_PageModeVerticalPosition     =  8050,

    PIDXPtr_CapConcurrentJrnRec          =  8501,
    PIDXPtr_CapConcurrentJrnSlp          =  8502,
    PIDXPtr_CapConcurrentRecSlp          =  8503,
    PIDXPtr_CapCoverSensor               =  8504,
    PIDXPtr_CapJrn2Color                 =  8505,
    PIDXPtr_CapJrnBold                   =  8506,
    PIDXPtr_CapJrnDhigh                  =  8507,
    PIDXPtr_CapJrnDwide                  =  8508,
    PIDXPtr_CapJrnDwideDhigh             =  8509,
    PIDXPtr_CapJrnEmptySensor            =  8510,
    PIDXPtr_CapJrnItalic                 =  8511,
    PIDXPtr_CapJrnNearEndSensor          =  8512,
    PIDXPtr_CapJrnPresent                =  8513,
    PIDXPtr_CapJrnUnderline              =  8514,
    PIDXPtr_CapRec2Color                 =  8515,
    PIDXPtr_CapRecBarCode                =  8516,
    PIDXPtr_CapRecBitmap                 =  8517,
    PIDXPtr_CapRecBold                   =  8518,
    PIDXPtr_CapRecDhigh                  =  8519,
    PIDXPtr_CapRecDwide                  =  8520,
    PIDXPtr_CapRecDwideDhigh             =  8521,
    PIDXPtr_CapRecEmptySensor            =  8522,
    PIDXPtr_CapRecItalic                 =  8523,
    PIDXPtr_CapRecLeft90                 =  8524,
    PIDXPtr_CapRecNearEndSensor          =  8525,
    PIDXPtr_CapRecPapercut               =  8526,
    PIDXPtr_CapRecPresent                =  8527,
    PIDXPtr_CapRecRight90                =  8528,
    PIDXPtr_CapRecRotate180              =  8529,
    PIDXPtr_CapRecStamp                  =  8530,
    PIDXPtr_CapRecUnderline              =  8531,
    PIDXPtr_CapSlp2Color                 =  8532,
    PIDXPtr_CapSlpBarCode                =  8533,
    PIDXPtr_CapSlpBitmap                 =  8534,
    PIDXPtr_CapSlpBold                   =  8535,
    PIDXPtr_CapSlpDhigh                  =  8536,
    PIDXPtr_CapSlpDwide                  =  8537,
    PIDXPtr_CapSlpDwideDhigh             =  8538,
    PIDXPtr_CapSlpEmptySensor            =  8539,
    PIDXPtr_CapSlpFullslip               =  8540,
    PIDXPtr_CapSlpItalic                 =  8541,
    PIDXPtr_CapSlpLeft90                 =  8542,
    PIDXPtr_CapSlpNearEndSensor          =  8543,
    PIDXPtr_CapSlpPresent                =  8544,
    PIDXPtr_CapSlpRight90                =  8545,
    PIDXPtr_CapSlpRotate180              =  8546,
    PIDXPtr_CapSlpUnderline              =  8547,
    PIDXPtr_CapCharacterSet              =  8548,
    PIDXPtr_CapTransaction               =  8549,
    PIDXPtr_CapJrnCartridgeSensor        =  8550,
    PIDXPtr_CapJrnColor                  =  8551,
    PIDXPtr_CapRecCartridgeSensor        =  8552,
    PIDXPtr_CapRecColor                  =  8553,
    PIDXPtr_CapRecMarkFeed               =  8554,
    PIDXPtr_CapSlpBothSidesPrint         =  8555,
    PIDXPtr_CapSlpCartridgeSensor        =  8556,
    PIDXPtr_CapSlpColor                  =  8557,
    PIDXPtr_CapMapCharacterSet           =  8558,
    PIDXPtr_CapConcurrentPageMode        =  8559,
    PIDXPtr_CapRecPageMode               =  8560,
    PIDXPtr_CapSlpPageMode               =  8561,
    PIDXPtr_CapRecRuledLine              =  8562,
    PIDXPtr_CapSlpRuledLine              =  8563,

    PIDXPtr_CharacterSetList             = 1008001,
    PIDXPtr_JrnLineCharsList             = 1008002,
    PIDXPtr_RecLineCharsList             = 1008003,
    PIDXPtr_SlpLineCharsList             = 1008004,
    PIDXPtr_ErrorString                  = 1008005,
    PIDXPtr_FontTypefaceList             = 1008006,
    PIDXPtr_RecBarCodeRotationList       = 1008007,
    PIDXPtr_SlpBarCodeRotationList       = 1008008,
    PIDXPtr_RecBitmapRotationList        = 1008009,
    PIDXPtr_SlpBitmapRotationList        = 1008010,
    PIDXPtr_PageModeArea                 = 1008011,
    PIDXPtr_PageModePrintArea            = 1008012
} OPOSPOSPrinterInternals;
